detect_ball:
  ros__parameters:
    x_min: 0
    x_max: 100
    y_min: 42
    y_max: 100
    h_min: 96
    h_max: 134
    s_min: 23
    s_max: 255
    v_min: 0
    v_max: 255
    sz_min: 1
    sz_max: 30
    tuning_mode: false
